### ISSUE TITLE
Invalid xml:base triggers url debug_assert

### ISSUE THREAD

**Issue by rillian** [feed-rs/feed-rs#141] opened 2022-01-06 17:51 UTC
The following snippet from `cargo fuzz` triggers a `debug_assert!` in url 2.2.2 [parser.rs:1241](https://github.com/servo/rust-url/blob/v2.2.2/url/src/parser.rs#L1241). Presumedly someone's skipped validating a type invariant, but I haven't investigated whether it's in feed-rs or the url crate.

```rust
    #[test]
    /// Report error for invalid input.
    fn fuzz_example() {
        let data: Vec<u8> = vec![
            0xdb, 0x3b, 0x3c, 0x66, 0x65, 0x65, 0x64, 0x3e,
            0x00, 0xfe, 0xff, 0x00, 0x00, 0x00, 0x3c, 0x1b,
            0x3b, 0x64, 0x22, 0x22, 0x0d, 0x78, 0x6d, 0x6c,
            0x3a, 0x62, 0x61, 0x73, 0x65, 0x0d, 0x0d, 0x3d,
            0x0a, 0x22, 0x0a, 0x0d, 0x0a, 0x0a, 0x0d, 0x66,
            0x69, 0x6c, 0x65, 0x3a, 0xff, 0x3b, 0xbf, 0x5b,
            0xbf, 0xbf, 0xbc, 0xff, 0xff, 0x0a, 0x53, 0x53,
            0x2b, 0x78, 0x3b, 0x22, 0x3c, 0x64, 0x3e, 0x2b,
            0x00, 0x00, 0x2b, 0x3c, 0xdb, 0x3b, 0x32, 0x65,
            0x64, 0x22, 0x22, 0x0d, 0x78, 0x6d, 0x6c, 0x3a,
            0x62, 0x61, 0x73, 0x65, 0x0d, 0x0d, 0x3d, 0x22,
            0x75, 0x7c, 0x3f, 0x0a, 0x34, 0x0a, 0xff, 0x22,
            0x34, 0x3a, 0xb5, 0x2f, 0x3c, 0x66, 0x65, 0x64,
            0x3e, 0x2b, 0x3c, 0xdb, 0x3b, 0x32, 0x65, 0x0d,
            0x78, 0x6d, 0x6c, 0x3a, 0x62, 0x61, 0x73, 0x65,
            0x0d, 0x0d, 0x3d, 0x22, 0x2e, 0x2e, 0x3f, 0x0a,
            0x3c, 0x3f, 0xff, 0x22, 0x34, 0x3a, 0xb5, 0x2f,
            0x2f, 0xff, 0xff, 0xfe, 0x01, 0xdb, 0x3b, 0x3c,
            0x66, 0x65,
        ];
        let result = parse(data.as_slice());
        assert!(result.is_err());
    }
```

**Comment by kevincox** [comment] 2022-02-21 14:37
This may be related that for feeds with `xml:base="http://"` the following error is returned: `unable to parse feed: no root element`.

Example URL: https://blog.plover.com/index.atom

Probably the correct behaviour here would be to ignore the unparsable attribute since nothing about feed parsing is strict.

**Comment by markpritchard** [comment] 2022-09-27 09:17
Thanks very much for the report @rillian , and apologies I forgot to comment on your original issue.
Looks like a dependency update fixed this, so I've included your fuzz result as a regression test and pushed up a PR.
Will close this shortly.

**Closed** 2022-09-27 09:19 UTC
