### ISSUE TITLE
feat: implement serde traits

### ISSUE THREAD

**Issue by andreacfromtheapp** [feed-rs/feed-rs#246] opened 2024-11-09 18:34 UTC
Hi,

I am implementing a free reader and de/serialization to pass around the data is kinda crucial.

I've seen a past issue and at the time chrono didn't implement serde either. https://github.com/feed-rs/feed-rs/issues/164

Now that chrono [DateTime does support serde now](https://docs.rs/chrono/0.4.38/chrono/struct.DateTime.html#impl-Serialize-for-DateTime%3CTz%3E), would it be possible to implement serialize and deserialize for feed-rs?

Please and thank you

**Comment by markpritchard** [comment] 2024-11-10 09:41
Hey @andreacfromtheapp , `serde` has been supported from v2.0.0 ;) 
https://github.com/feed-rs/feed-rs/releases/tag/v2.0.0

**Comment by andreacfromtheapp** [comment] 2024-11-10 09:49
what am I doing wrong here then? https://github.com/crab-apps/crab-news/blob/main/shared/src/app/feeds.rs

Cargo complains about Feed not supporting Serialize and Deserialize.

consider this is my very first Rust app after finishing The Book and that I am no professional (yet)

**Comment by andreacfromtheapp** [comment] 2024-11-10 10:12
ps: consider I've only just begain with `app/feed.rs`. Take a look at https://github.com/crab-apps/crab-news/blob/main/shared/src/app/subscriptions.rs to see where I am going with this

**Comment by andreacfromtheapp** [comment] 2024-11-11 07:59
Hey @markpritchard,

sorry to bother with this, I'd like to understand. You have reopened the issue, so there must be something. I am a noob but if it's trivial I could give it a go. E.g: I checked the other crate I use and to a novice like me it seems a matter of deriving the traits? https://docs.rs/opml/1.1.6/opml/

If I am mistaken. I apologize and I would appreciate knowing the status or if there's anything I can do to help.

Please and thank you

**Comment by markpritchard** [comment] 2024-11-11 10:08
Hi @andreacfromtheapp , I reopened it as I closed it accidentally (I didn't just want to close the ticket without a response from you).
I'm not sure what the problem is in your crate, but I'll try to find some time over the next few days to take a look (feed-rs isn't my day job, so it can take me a little time)

**Comment by andreacfromtheapp** [comment] 2024-11-11 10:17
Hi @markpritchard 

thanks for your kind reply, I appreciate :)

I understand the burden of open source maintainers and people expecting things. No worries and take your time. I just wanted to check with you :)

The problem I am having is that I am trying to use `Feed` from model and `cargo` complaints it doesn't implement `Serialize` and `Deserialize`:

```rust
use feed_rs::model::Feed;
use serde::{Deserialize, Serialize};

#[derive(Default, Debug, Serialize, Deserialize, PartialEq, Clone)]
pub struct Feeds {
    pub feeds: Vec<Feed>,
}
```

I tried looking into the other crate I use (`opml`) and it simpy `derive`s them, hence my attempt/suggestion from the previous message. If you don't have time and it turns out to be this simple, I can give it a go :) (mind I am a noob).

Cheers and thanks again for now

ps: I pointed you to the otehr crate (`subscriptions`) just as a reference and to see which kind of use I'd make of `feed-rs` since the `feeds.rs` code is non-existent. Not that you need to examine the code but it may help see the issue?

**Comment by markpritchard** [comment] 2024-11-12 04:37
Can you post the error you are seeing @andreacfromtheapp ?

I checked out `a1510d769f54bb421365759b59ca819a1639992d` from your repo, and it builds cleanly.

**Comment by andreacfromtheapp** [comment] 2024-11-12 07:05
@markpritchard try uncommenitng https://github.com/crab-apps/crab-news/blob/main/shared/src/app.rs#L18-L19 :)

at the moment the module is not being used because of the error.

**Comment by andreacfromtheapp** [comment] 2024-11-12 13:01
here's a `cargo check` with those lines uncommented just in case

```rust
   Compiling shared v0.1.0 (/Users/andreacfromtheapp/IT/Rust/projects/crab-news/shared)
error[E0277]: the trait bound `Feed: Serialize` is not satisfied
    --> shared/src/app/feeds.rs:13:26
     |
13   | #[derive(Default, Debug, Serialize, Deserialize, PartialEq, Clone)]
     |                          ^^^^^^^^^ the trait `Serialize` is not implemented for `Feed`, which is required by `Vec<Feed>: Serialize`
14   | pub struct Feeds {
15   |     pub feeds: Vec<Feed>,
     |     --- required by a bound introduced by this call
     |
     = note: for local types consider adding `#[derive(serde::Serialize)]` to your `Feed` type
     = note: for types from other crates check whether the crate offers a `serde` feature flag
     = help: the following other types implement trait `Serialize`:
               &'a T
               &'a mut T
               ()
               (T,)
               (T0, T1)
               (T0, T1, T2)
               (T0, T1, T2, T3)
               (T0, T1, T2, T3, T4)
             and 218 others
     = note: required for `Vec<Feed>` to implement `Serialize`
note: required by a bound in `app::_::_serde::ser::SerializeStruct::serialize_field`
    --> /Users/andreacfromtheapp/.cargo/registry/src/index.crates.io-6f17d22bba15001f/serde-1.0.213/src/ser/mod.rs:1867:21
     |
1865 |     fn serialize_field<T>(&mut self, key: &'static str, value: &T) -> Result<(), Self::Error>
     |        --------------- required by a bound in this associated function
1866 |     where
1867 |         T: ?Sized + Serialize;
     |                     ^^^^^^^^^ required by this bound in `SerializeStruct::serialize_field`
     = note: this error originates in the derive macro `Serialize` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the trait bound `Feed: Deserialize<'_>` is not satisfied
    --> shared/src/app/feeds.rs:15:16
     |
15   |     pub feeds: Vec<Feed>,
     |                ^^^^^^^^^ the trait `Deserialize<'_>` is not implemented for `Feed`, which is required by `Vec<Feed>: Deserialize<'_>`
     |
     = note: for local types consider adding `#[derive(serde::Deserialize)]` to your `Feed` type
     = note: for types from other crates check whether the crate offers a `serde` feature flag
     = help: the following other types implement trait `Deserialize<'de>`:
               &'a Path
               &'a [u8]
               &'a camino::Utf8Path
               &'a serde_bytes::bytearray::ByteArray<N>
               &'a serde_bytes::bytes::Bytes
               &'a str
               ()
               (T,)
             and 232 others
     = note: required for `Vec<Feed>` to implement `Deserialize<'_>`
note: required by a bound in `next_element`
    --> /Users/andreacfromtheapp/.cargo/registry/src/index.crates.io-6f17d22bba15001f/serde-1.0.213/src/de/mod.rs:1732:12
     |
1730 |     fn next_element<T>(&mut self) -> Result<Option<T>, Self::Error>
     |        ------------ required by a bound in this associated function
1731 |     where
1732 |         T: Deserialize<'de>,
     |            ^^^^^^^^^^^^^^^^ required by this bound in `SeqAccess::next_element`

error[E0277]: the trait bound `Feed: Deserialize<'_>` is not satisfied
    --> shared/src/app/feeds.rs:15:16
     |
15   |     pub feeds: Vec<Feed>,
     |                ^^^^^^^^^ the trait `Deserialize<'_>` is not implemented for `Feed`, which is required by `Vec<Feed>: Deserialize<'_>`
     |
     = note: for local types consider adding `#[derive(serde::Deserialize)]` to your `Feed` type
     = note: for types from other crates check whether the crate offers a `serde` feature flag
     = help: the following other types implement trait `Deserialize<'de>`:
               &'a Path
               &'a [u8]
               &'a camino::Utf8Path
               &'a serde_bytes::bytearray::ByteArray<N>
               &'a serde_bytes::bytes::Bytes
               &'a str
               ()
               (T,)
             and 232 others
     = note: required for `Vec<Feed>` to implement `Deserialize<'_>`
note: required by a bound in `next_value`
    --> /Users/andreacfromtheapp/.cargo/registry/src/index.crates.io-6f17d22bba15001f/serde-1.0.213/src/de/mod.rs:1871:12
     |
1869 |     fn next_value<V>(&mut self) -> Result<V, Self::Error>
     |        ---------- required by a bound in this associated function
1870 |     where
1871 |         V: Deserialize<'de>,
     |            ^^^^^^^^^^^^^^^^ required by this bound in `MapAccess::next_value`

error[E0277]: the trait bound `Feed: Deserialize<'_>` is not satisfied
  --> shared/src/app/feeds.rs:13:37
   |
13 | #[derive(Default, Debug, Serialize, Deserialize, PartialEq, Clone)]
   |                                     ^^^^^^^^^^^ the trait `Deserialize<'_>` is not implemented for `Feed`, which is required by `Vec<Feed>: Deserialize<'_>`
   |
   = note: for local types consider adding `#[derive(serde::Deserialize)]` to your `Feed` type
   = note: for types from other crates check whether the crate offers a `serde` feature flag
   = help: the following other types implement trait `Deserialize<'de>`:
             &'a Path
             &'a [u8]
             &'a camino::Utf8Path
             &'a serde_bytes::bytearray::ByteArray<N>
             &'a serde_bytes::bytes::Bytes
             &'a str
             ()
             (T,)
           and 232 others
   = note: required for `Vec<Feed>` to implement `Deserialize<'_>`
note: required by a bound in `app::_::_serde::__private::de::missing_field`
  --> /Users/andreacfromtheapp/.cargo/registry/src/index.crates.io-6f17d22bba15001f/serde-1.0.213/src/private/de.rs:25:8
   |
23 | pub fn missing_field<'de, V, E>(field: &'static str) -> Result<V, E>
   |        ------------- required by a bound in this function
24 | where
25 |     V: Deserialize<'de>,
   |        ^^^^^^^^^^^^^^^^ required by this bound in `missing_field`
   = note: this error originates in the derive macro `Deserialize` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0277`.
error: could not compile `shared` (lib) due to 4 previous errors
warning: build failed, waiting for other jobs to finish...
error: could not compile `shared` (lib) due to 4 previous errors
```

**Comment by snark** [comment] 2024-11-17 00:58
This just bit me (trying to pass a Vec of Entries into a Tera template context) -- it looks like `2e6b7a019c1d1dad08b96fd28d22b2a8646bc8e6` was reverted at some point? I don't see it in the `main` branch, nor do I see the traits on Feed, etc.

**Comment by markpritchard** [comment] 2024-11-17 06:56
Thanks @snark , that is very strange as https://github.com/feed-rs/feed-rs/pull/227/commits clearly shows it merging into master.
But I can't check this PR out any more either. I'll see if I can reconstruct it, as this is definitely meant to be supported.

**Comment by andreacfromtheapp** [comment] 2024-11-17 07:55
Hi, 

a quick one to notify you that in the meantime I'm trying other crates and if you want to test it you should implement the `Vec<Feed>` as above or if you need it let me know that I'll make a branch.

I hope you can solve this because I like your crate better as it integrates both RSS and Atom in a smart way with the parser and all.

**Comment by markpritchard** [comment] 2024-11-17 08:11
No worries @andreacfromtheapp , feel free to use whatever works. 
I managed to resurrect the old patch in #247 so just need to clean up the tests and should be able to merge it in again.

Not quite sure how that single commit managed to disappear, super strange. I probably stuffed up a merge/rebase/push somewhere.

**Comment by andreacfromtheapp** [comment] 2024-11-17 08:14
I appreciate the courtesy @markpritchard , I wanna use yours as I believe it's what I need :) (at least until I may realize I am wrong :P)

**Comment by markpritchard** [comment] 2024-11-17 08:21
feed-rs is used by https://apps.gnome.org/NewsFlash/ (shipped in Gnome Circle), so it gets a fair bit of use. Hopefully its seen most of the poorly formatted feeds out there on the net, but there are always new problems. :)

**Comment by markpritchard** [comment] 2024-11-17 08:23
#247 is ready to go, so merging that will close this issue. I'll open it again, just in case you have more problems.

Feel free to test it on the sha that merges, and I'll release 2.2.0 shortly.

**Comment by andreacfromtheapp** [comment] 2024-11-17 08:31
> feed-rs is used by https://apps.gnome.org/NewsFlash/ (shipped in Gnome Circle), so it gets a fair bit of use. Hopefully its seen most of the poorly formatted feeds out there on the net, but there are always new problems. :)

thanks, I didn't know this :) I will bookmark it for ideas. Right now I am basically implementing a _NetNewsWire clone_ but in Rust and multi-platform desktop and mobile.

**Comment by markpritchard** [comment] 2024-11-17 08:33
v2.2.0 is out now on crates.io ... I haven't tested your app with it, but as @snark mentioned, the annotations were not present given that commit had disappeared. Quite a head scratcher (I can't find the release 2.1.1 commit in history either :shrug: ... but its in the GitHub UI??).

**Comment by markpritchard** [comment] 2024-11-17 09:03
Great, thanks for checking.

I'll close this, but feel free to raise another issue if you run into other problems.

**Closed by markpritchard** 2024-11-17 09:03 UTC

**Comment by snark** [comment] 2024-11-18 02:17
@markpritchard Worked perfectly for me as well, thanks!

**Comment by markpritchard** [comment] 2024-11-18 02:27
Great to hear, thanks @snark
