### ISSUE TITLE
Handle invalid rss feeds

### ISSUE THREAD

**Issue by ayrat555** [feed-rs/feed-rs#45] opened 2020-05-23 16:47 UTC
Reddit generates invalid rss feeds. Can you make parser skip invalid items?

https://www.reddit.com/r/memes.rss

**Comment by markpritchard** [comment] 2020-05-24 22:01
Hi @ayrat555 , there was a fix merged recently for invalid dates in Atom feeds and testing with reddit on `cdd83a40e4c51c9b9401feddb7fcc395a0a4de15` it parses correctly.

I'll be releasing 0.2.4 shortly with this fix, along with a regression test case to ensure Reddit parses correctly in the future too.

**Comment by ayrat555** [comment] 2020-06-06 04:43
I just tried a master branch and it doesn't work for me with `NoFeedRoot` as well as https://github.com/feed-rs/feed-rs/issues/53

I think the issue should be re-opened

**Comment by markpritchard** [comment] 2020-06-06 05:15
Curious - do you have the raw XML that fails @ayrat555 ? It would help reproduce and fix the issue.

**Comment by markpritchard** [comment] 2020-06-06 10:57
Suspect this was due to redirects, similar to #53 . Feel free to comment + upload the examples if this is not the case @ayrat555

**Closed by markpritchard** 2020-06-06 10:57 UTC

**Comment by ayrat555** [comment] 2020-06-06 11:47
The issue was caused by Reddit API. It needed a user-agent header. I'm sorry for the inconvenience.

I completely migrated el_monitorro to feed-rs as parsing backend

**Comment by markpritchard** [comment] 2020-06-06 11:56
Great, thanks for the update @ayrat555 - great to hear you find the library useful!
